# Generated by Django 3.0.8 on 2020-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='Demo biography.'),
            preserve_default=False,
        ),
    ]
