# Generated by Django 3.0.8 on 2020-08-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1538391386255-8285e0bf2383?ixlib=rb-1.2.1&auto=format&fit=crop&w=1531&q=80', max_length=200),
            preserve_default=False,
        ),
    ]
