# Generated by Django 3.0.8 on 2020-08-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200813_0651'),
        ('users', '0005_auto_20200815_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_categories',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
