# Generated by Django 3.0.8 on 2020-08-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_favourite_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favourite_categories',
            new_name='favourite_topics',
        ),
    ]
