# Generated by Django 3.0.8 on 2020-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
