# Generated by Django 3.0.8 on 2020-08-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200808_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='last_updated',
        ),
    ]
