# Generated by Django 3.0.8 on 2020-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_newsstory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
