# Generated by Django 3.0.8 on 2020-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsstory_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
