# Generated by Django 3.0.8 on 2020-08-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200812_1903'),
        ('news', '0009_newsstory_modified'),
    ]

    operations = [
    ]
