# Generated by Django 3.0.8 on 2020-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_merge_20200813_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
